export const APP_VERSION = 'interview-stage-4';

export const COLORS = {
  pink: { hex: 0xff68fd, rgb: [255, 104, 253] },
  yellow: { hex: 0xffe528, rgb: [255, 229, 40] },
  blue: { hex: 0x15befc, rgb: [21, 190, 252] },
};

export const COLOR_KEYS = Object.keys(COLORS);

export const LEVELS = [
  {
    name: '永恒号',
    nameEn: 'Endurance',
    maxType: 1,
    winHits: 1,
    blackHoleDistance: 70,
    speedRamp: 0.18,
    boostChance: 0,
    movingChance: 0,
    splitMovingChance: 0,
    movingAmplitude: 0,
    movingSpeedScale: 1,
    gapMin: 3.75,
    gapMax: 7.5,
    mechanics: ['长轨道', '黑洞目标'],
    desc: '1 次命中后开启黑洞',
  },
  {
    name: '水星',
    nameEn: 'Miller',
    maxType: 2,
    winHits: 3,
    blackHoleDistance: 110,
    speedRamp: 0.22,
    boostChance: 0.06,
    movingChance: 0.18,
    splitMovingChance: 0,
    movingAmplitude: 0.95,
    movingSpeedScale: 0.85,
    gapMin: 3.75,
    gapMax: 7.1,
    mechanics: ['双色轨道', '移动轨道'],
    desc: '3 次命中后开启黑洞',
  },
  {
    name: '曼恩星球',
    nameEn: 'Mann',
    maxType: 3,
    winHits: 5,
    blackHoleDistance: 140,
    speedRamp: 0.34,
    boostChance: 0.14,
    movingChance: 0.22,
    splitMovingChance: 0,
    movingAmplitude: 1.18,
    movingSpeedScale: 1,
    gapMin: 3.95,
    gapMax: 7.3,
    mechanics: ['三色轨道', '加速轨道', '超空间'],
    desc: '5 次命中后开启黑洞',
  },
  {
    name: '土星',
    nameEn: 'Saturn',
    maxType: 3,
    winHits: 7,
    blackHoleDistance: 180,
    speedRamp: 0.46,
    boostChance: 0.18,
    movingChance: 0.24,
    splitMovingChance: 0.16,
    movingAmplitude: 1.42,
    movingSpeedScale: 1.16,
    gapMin: 4.2,
    gapMax: 7.7,
    mechanics: ['交错轨道', '速度爬升', '超空间'],
    desc: '7 次命中后开启黑洞',
  },
  {
    name: '卡冈图雅',
    nameEn: 'Gargantua',
    maxType: 3,
    winHits: 9,
    blackHoleDistance: 230,
    speedRamp: 0.58,
    boostChance: 0.22,
    movingChance: 0.28,
    splitMovingChance: 0.26,
    movingAmplitude: 1.65,
    movingSpeedScale: 1.34,
    gapMin: 4.4,
    gapMax: 8.1,
    mechanics: ['终局冲刺', '交错轨道', '高速连击'],
    desc: '9 次命中后开启黑洞',
  },
];
